server:
  port: 8087

spring:
  data:
    mongodb:
      uri: mongodb+srv://mugoksazi:Ank55ist@cluster0.qdyakll.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: UserDB

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true

