package com.usmobile.services.dataUsageService.domain;

import com.usmobile.services.dataUsageService.constant.DataUsageConstants;
import com.usmobile.shared.model.data.BaseData;
import lombok.Builder;
import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.CompoundIndex;

import java.time.LocalDateTime;
import java.util.Date;
import java.util.UUID;

/***
 * String: id (primary key, auto-generated by MongoDB)
 *
 * String: mdn (the phone number of a customer)
 *
 * Date: startDate (the start date of a billing cycle)
 *
 * Date: endDate (the end date of a billing cycle)
 *
 * String: userId (foreign key to the id of the user collection)
 */

@Data
@Builder
@CompoundIndex(name = "userId_mdn_idx", def = "{'userId' : 1, 'mdn' : 1}")
public class Cycle extends BaseData {
    @Id
    String id;
    String cycleId;
    String mdn;
    LocalDateTime startDate;
    LocalDateTime endDate;
    String userId;

    public String generateId(){return DataUsageConstants.idPrefixes.CYCLE_ID_PREFIX + UUID.randomUUID();
    }
}
