server:
  port: 8089

spring:
  data:
    mongodb:
      uri: mongodb+srv://mugoksazi:Ank55ist@cluster0.qdyakll.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: MDNDB

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true

    consumer:
      bootstrap-servers: localhost:9092
      group-id: user-data
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.usmobile.shared.model.data.UserEventDto
        enable.idempotence: true
